services:
  lavalink:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build:  lavalink/.
    hostname: lavalink
    volumes:
      - ./lavalink:/home/
    ports:
      - "443:443"
  discord_sound_streamer:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build: .
    environment:
      - WAIT_FOR_LAVALINK=True
      - LAVALINK_HOST=lavalink
    volumes:
      - .:/code

    depends_on:
      - "lavalink"
