services:
  lavalink:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build:  lavalink/.
    hostname: lavalink
    volumes:
      - ./lavalink:/home/
    ports:
      - "40443:40443"
  discord_sound_streamer:
    env_file:
      - .env.local
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build: .
    environment:
      - WAIT_FOR_LAVALINK=True
      - LAVALINK_HOST=lavalink
      - PO_TOKEN=${PO_TOKEN}
      - VISITOR_DATA=${VISITOR_DATA}
    volumes:
      - .:/code

    depends_on:
      - "lavalink"
