name: Lint
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
